// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a279b50e-3d78-485a-a7f9-e9b7ba1ab175"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 2, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2521),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("3f22892a-33fb-4370-86b8-76b9bbdc00ec"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 3, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2530),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("2dcbff29-b09a-4084-a5a7-ef1b31ac8133"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 5, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2533),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("a947ed77-c2f7-40cb-bd1f-4ea710d5b4a3"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 6, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2535),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("032e36a7-2959-4939-bffb-153a17d8c11a"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 7, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2536),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("60016532-b76f-4b16-8b5a-3f7f05c86df3"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 8, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2546),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("48373c4f-47db-4137-848c-e254674af5d0"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 9, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2547),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("6ab7b11f-f386-4863-bd80-4a6b1f948368"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 10, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2549),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("0394107e-95b6-4db4-be03-b45c1152d8f8"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 11, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2551),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("f057e460-057d-40b4-856b-77b5fccf75f9"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 12, 29, 1, 51, 24, 129, DateTimeKind.Utc).AddTicks(2552),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
